version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Presentation/API/Dockerfile
    container_name: my-api
    ports:
      - "5120:80" # API on http://localhost:5120
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__RagDb=Host=db;Port=5432;Database=ragDb;Username=iasgarov;Password=Az010203
    networks:
      - backend

  db:
    image: ankane/pgvector:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: iasgarov
      POSTGRES_PASSWORD: Az010203
      POSTGRES_DB: ragDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ixtiyar.esgerov78@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: Az010203
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - backend

networks:
  backend:

volumes:
  postgres_data:
